In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/dashboard_summary_final.csv")

df

,amfi_code,start_nav,end_nav,return_pct,volatility,sharpe_ratio,scheme_name
0,118632,12.2191,106.1272,768.535326,0.166915,0.948544,Nippon India Large Cap Fund
1,119551,102.2299,161.3775,57.857437,0.087114,0.062948,SBI Bluechip Fund
2,120503,13.6318,113.6849,733.968368,0.009644,0.065438,ICICI Prudential Bluechip Fund
3,120841,30.5643,281.1083,819.727591,0.154202,1.108882,Kotak Bluechip Fund
4,125497,12.7775,214.6767,1580.115046,0.152034,1.523487,HDFC Top 100 Fund

In [2]:
df.sort_values(
    "return_pct",
    ascending=False
)

,amfi_code,start_nav,end_nav,return_pct,volatility,sharpe_ratio,scheme_name
4,125497,12.7775,214.6767,1580.115046,0.152034,1.523487,HDFC Top 100 Fund
3,120841,30.5643,281.1083,819.727591,0.154202,1.108882,Kotak Bluechip Fund
0,118632,12.2191,106.1272,768.535326,0.166915,0.948544,Nippon India Large Cap Fund
2,120503,13.6318,113.6849,733.968368,0.009644,0.065438,ICICI Prudential Bluechip Fund
1,119551,102.2299,161.3775,57.857437,0.087114,0.062948,SBI Bluechip Fund

In [3]:
df.sort_values(
    "sharpe_ratio",
    ascending=False
)

,amfi_code,start_nav,end_nav,return_pct,volatility,sharpe_ratio,scheme_name
4,125497,12.7775,214.6767,1580.115046,0.152034,1.523487,HDFC Top 100 Fund
3,120841,30.5643,281.1083,819.727591,0.154202,1.108882,Kotak Bluechip Fund
0,118632,12.2191,106.1272,768.535326,0.166915,0.948544,Nippon India Large Cap Fund
2,120503,13.6318,113.6849,733.968368,0.009644,0.065438,ICICI Prudential Bluechip Fund
1,119551,102.2299,161.3775,57.857437,0.087114,0.062948,SBI Bluechip Fund

Performance Analytics Findings

1. HDFC Top 100 Fund ranks first.
2. Kotak Bluechip ranks second.
3. Sharpe ratio confirms HDFC leadership.
4. ICICI offers moderate return.
5. SBI has weakest performance.